/**
 * Every UI string lives here so the English switch can be added later.
 * Status words (SOLD, NEW, DROP, BOOST) stay Latin in both languages.
 */
export const ka = {
  home: "მთავარი",
  homeLabel: "DEADSTOCK — მთავარი",
  search: "ძებნა",
  searchLabel: "ძებნა — ქართულად ან ლათინურად",
  searchPlaceholder: "რას ეძებ?",
  sell: "გაყიდე",
  sellArrow: "გაყიდე →",
  map: "რუკა",
  saved: "შენახული",
  save: "შენახვა",
  menu: "მენიუ",
  category: "კატეგორია",
  size: "ზომა",
  maxPrice: "მაქსიმალური ფასი",
  justPosted: "ახლახან დაიდო",
  onHold: "დაჯავშნილია",
  video: "ვიდეო",
  verified: "ვერიფიცირებული",
  whatIs: "რა არის DEADSTOCK?",
  clear: "გასუფთავება",
  thatsAll: "სულ ესაა.",
  yet: "ჯერ.",
  priceInDm: "ფასი DM-ში",

  /* ---- per screen ---- */
  itemPage: {
    price: "ფასი",
    posted: "დაიდო",
    size: "ზომა",
    condition: "მდგომარეობა",
    brand: "ბრენდი",
    category: "კატეგორია",
    originalPost: "ორიგინალი პოსტი",
    moreItems: "სხვა ნივთები →",
    caption: "პოსტის ტექსტი",
    videoOnIg: "ვიდეო Instagram-ზე",
    // relative "posted" time
    justNow: "ახლა",
    min: "წთ",
    hour: "სთ",
    yesterday: "გუშინ",
    day: "დ",
  },
  shopPage: {
    address: "მისამართი",
    available: "ხელმისაწვდომი",
    sold: "გაყიდული",
    share: "გაზიარება",
    copied: "ბმული დაკოპირდა",
    noneAvailable: "ხელმისაწვდომი ნივთი არ არის",
    nextDrop: "NEXT DROP SOON",
    allShops: "ყველა მაღაზია →",
    instagram: "Instagram",
  },
  searchPage: {
    title: "ძებნა · DEADSTOCK.ge",
    back: "უკან",
    filters: "ფილტრები",
    results: "შედეგები",
    price: "ფასი",
    items: "ITEMS",
    sizeLegend: "SIZE",
    priceLegend: "PRICE",
  },
  savedPage: {
    title: "შენახული",
    filter: "ფილტრი",
    all: "ყველა",
    available: "ხელმისაწვდომი",
    empty: "ჯერ ცარიელია.",
    browse: "BROWSE",
    failed: "ვერ ჩაიტვირთა.",
    retry: "თავიდან ცდა",
  },
  mapScreen: {
    title: "თრიფთ-კრაული",
    back: "უკან",
    shops: "მაღაზიები",
    map: "რუკა",
    shop: "მაღაზია",
    route: "მარშრუტი",
    items: "ITEMS",
    empty: "რუკაზე ჯერ მაღაზიები არ არის.",
  },
  mapPage: {
    title: "თრიფთ-კრაული — DEADSTOCK.ge",
  },
  sellPage: {
    home: "DEADSTOCK — მთავარი",
    kicker: "SELL ON DEADSTOCK",
    h1a: "Instagram დააკავშირე.",
    h1b: "დანარჩენს ჩვენ ვიზამთ.",
    onlyA: "მხოლოდ ",
    onlyB: " ანგარიში",
    connect: "დაკავშირება",
    back: "← უკან",
    errPersonal: "Business / Creator?",
    errFailed: "Instagram-თან დაკავშირება ვერ მოხერხდა. სცადე თავიდან.",
  },
  notFound: {
    title: "აქ არაფერია",
    home: "← მთავარი",
  },
  dash: {
    home: "DEADSTOCK — მთავარი",
    shopBadge: "SHOP",
    shopBadgeDesk: "SHOP PANEL",
    logout: "გასვლა",
    live: "LIVE",
    paused: "PAUSED",
    syncLabel: "SYNC",
    syncNow: "სინქრონიზაცია",
    syncRunning: "სინქი…",
    syncNever: "—",
    syncFailed: "ბოლო სინქი ვერ მოხერხდა",
    syncMetaTitle: "ბოლო სინქი · ნივთები",
    auto: "AUTO",
    autoTitle: "ავტო-გამოქვეყნება: ახალი პოსტი პირდაპირ საიტზე",
    copyLink: "ბმულის კოპირება",
    copied: "დაკოპირდა",
    pendingH: "ახალი",
    allH: "ყველა",
    allGood: "ყველაფერი ✓",
    approve: "დადასტურება",
    reject: "უარყოფა",
    markSold: "გაყიდულად მონიშვნა",
    untitled: "უსათაურო",
    noPrice: "ფასი —",
    size: "ზომა",
    colItem: "ნივთი",
    edit: "რედაქტირება",
    back: "უკან",
    save: "SAVE",
    viewOnSite: "ნახვა საიტზე",
    igPost: "IG პოსტი",
    status: "სტატუსი",
    available: "ხელმისაწვდომი",
    reserved: "დაჯავშნილი",
    sold: "გაყიდული",
    price: "ფასი",
    photos: "ფოტოები",
    details: "დეტალები",
    customSize: "სხვა ზომა",
    minutes: "წთ",
    hours: "სთ",
    days: "დღე",
    now: "ახლა",
  },
} as const;

export const t = ka;
